# Generated by Django 5.1.6 on 2026-06-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0002_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('FICCAO', 'Ficção'), ('FANTASIA', 'Fantasia'), ('ROMANCE', 'Romance'), ('MISTERIO', 'Mistério'), ('DRAMA', 'Drama'), ('HISTORICO', 'Histórico'), ('BIOGRAFIA', 'Biografia'), ('TERROR', 'Terror'), ('AVENTURA', 'Aventura'), ('AUTOAJUDA', 'Autoajuda'), ('CULINARIA', 'Culinária'), ('POESIA', 'Poesia'), ('FICCAO_CIENTIFICA', 'Ficção Científica'), ('OUTROS', 'Outros')], max_length=100),
        ),
    ]
